# Generated by Django 3.2.7 on 2021-09-18 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_footprint', models.IntegerField()),
                ('get_started_section_score', models.IntegerField()),
                ('travel_section_score', models.IntegerField()),
                ('home_section_score', models.IntegerField()),
                ('food_section_score', models.IntegerField()),
                ('shopping_section_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Carbon Footprint',
            },
        ),
    ]
