# Generated by Django 3.2.7 on 2021-09-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon_footprint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonfootprint',
            name='id',
        ),
        migrations.AddField(
            model_name='carbonfootprint',
            name='footprint_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
